### ISSUE TITLE
pg_notify

### ISSUE THREAD

**Issue by SanjarBakhramovich** [MatthewJamesBoyle/golang-interview-prep#4]
docker-compose up
[+] Running 15/1
 ✔ postgres 14 layers [⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                        350.0s 
[+] Running 1/1
 ✔ Container golang-interview-prep-postgres-1  Recreated                                                                                                                               1.1s 
Attaching to postgres-1
postgres-1  | 
postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres-1  | 
postgres-1  | 2024-03-18 07:52:33.359 UTC [1] FATAL:  could not open directory "**pg_notify**": No such file or directory
postgres-1  | 2024-03-18 07:52:33.360 UTC [1] LOG:  database system is shut down
postgres-1 exited with code 0

**Comment by iambpn** [comment]
+1 same issue while running `docker compose up`

**Comment by ODawah** [comment]
I faced the same problem and the solution that worked for me was changing the name of the volume 
```yaml
    volumes:
      - ./data1:/var/lib/postgresql/data
```
